Repository maxspahn/gym_envs_urdf, pull requests merged in 2021-12, with the labels that each got.

#20 Ft remove inverse dynamics
  albertReacher/envs/acc.py
  albertReacher/envs/albertReacherEnv.py
  albertReacher/envs/tor.py
  albertReacher/envs/vel.py
  albertReacher/resources/albertRobot.py
  examples/albert.py
  examples/mobile_reacher.py
  mobileReacher/envs/acc.py
  mobileReacher/resources/mobileRobot.py
  tiagoReacher/resources/tiagoRobot.py
Labels: bug

#22 Ft join resources
  albertReacher/resources/albertRobot.py
  mobileReacher/resources/mobileRobot.py
  nLinkUrdfReacher/resources/nLinkRobot.py
  pandaReacher/resources/pandaRobot.py
  pandaReacher/resources/pandaWithGripper_working.urdf
  pandaReacher/resources/scene.py
  pointRobotUrdf/resources/pointRobot.py
  tiagoReacher/resources/tiagoRobot.py
  urdfCommon/abstractRobot.py
Labels: enhancement, cleanUp

#25 Cleans up reset method
  albertReacher/envs/albertReacherEnv.py
  albertReacher/resources/albert.urdf
  mobileReacher/envs/mobileReacherEnv.py
  mobileReacher/resources/plane.py
  mobileReacher/resources/scene.py
  nLinkUrdfReacher/envs/nLinkUrdfReacherEnv.py
  nLinkUrdfReacher/resources/plane.py
  nLinkUrdfReacher/resources/testUrdf.py
  pandaReacher/envs/pandaReacherEnv.py
  pandaReacher/resources/plane.py
  pointRobotUrdf/envs/pointRobotEnv.py
  pointRobotUrdf/resources/plane.py
  tiagoReacher/envs/tiagoReacherEnv.py
  tiagoReacher/resources/plane.py
  tiagoReacher/resources/plane.urdf
  urdfCommon/abstractRobot.py
  urdfCommon/meshes/checker_blue.png
  urdfCommon/meshes/plane.mtl
  urdfCommon/meshes/plane.obj
  urdfCommon/plane.py
  urdfCommon/plane.urdf
  urdfCommon/urdfEnv.py
Labels: enhancement, cleanUp

#27 Create user input example
  README.md
  examples/keyboard_input_example.py
  keyboardInput/.gitignore
  keyboardInput/keyboard_input_responder.py
  setup.py
Labels: enhancement

#23 Adds example on usage sphere obstacles and urdf obstacles in environments.
  README.md
  requirements_scenes.txt
  setup.py
  urdfCommon/abstractRobot.py
  urdfCommon/urdfEnv.py
  urdfGymExamples/.gitignore
  urdfGymExamples/albert.py
  urdfGymExamples/keyboard_input_example.py
  urdfGymExamples/mobile_reacher.py
  urdfGymExamples/nLinkUrdf_reacher.py
  urdfGymExamples/panda_reacher.py
  urdfGymExamples/pointRobot_example.py
  urdfGymExamples/sceneObjects/goal.py
  urdfGymExamples/sceneObjects/obstacleData/duck.obj
  urdfGymExamples/sceneObjects/obstacleData/duck.urdf
  urdfGymExamples/sceneObjects/obstacleData/duck_vhacd.obj
  urdfGymExamples/sceneObjects/obstacleData/sphere_goal.urdf
  urdfGymExamples/sceneObjects/obstacleData/sphere_smooth.obj
  urdfGymExamples/sceneObjects/obstacles.py
  urdfGymExamples/tiago.py
Labels: enhancement

#31 Adds boxerRobot.
  boxerRobot/.gitignore
  boxerRobot/__init__.py
  boxerRobot/envs/.gitignore
  boxerRobot/envs/__init__.py
  boxerRobot/envs/acc.py
  boxerRobot/envs/boxerRobotEnv.py
  boxerRobot/envs/vel.py
  boxerRobot/resources/.gitignore
  boxerRobot/resources/boxer.urdf
  boxerRobot/resources/boxerRobot.py
  boxerRobot/resources/meshes/collision/chassis_link.STL
  boxerRobot/resources/meshes/collision/extrusion.stl
  boxerRobot/resources/meshes/collision/internal_link.STL
  boxerRobot/resources/meshes/collision/lift_link.STL
  boxerRobot/resources/meshes/collision/rotacastor_left_link.STL
  boxerRobot/resources/meshes/collision/rotacastor_right_link.STL
  boxerRobot/resources/meshes/collision/top_plate.stl
  boxerRobot/resources/meshes/collision/top_plate_collision.stl
  boxerRobot/resources/meshes/collision/wheel_left_link.STL
  boxerRobot/resources/meshes/collision/wheel_right_link.STL
  boxerRobot/resources/meshes/visual/chassis_link.dae
  boxerRobot/resources/meshes/visual/internal_link.dae
  boxerRobot/resources/meshes/visual/lift_link.dae
  urdfGymExamples/boxer.py
Labels: enhancement
